declare type SvgNames =
  | 'arrow-chevron-down'
  | 'arrow-chevron-left'
  | 'arrow-chevron-right'
  | 'email'
  | 'fb'
  | 'instagram'
  | 'logo-back'
  | 'logo-bottom'
  | 'logo-top'
  | 'twitter'
  | 'vk-no-bg'
  | 'vk'
